"""change datetime in create_at, update_at

Revision ID: 9a6df75a733a
Revises: adbe9f4e442a
Create Date: 2026-05-29 14:51:36.337298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6df75a733a'
down_revision: Union[str, Sequence[str], None] = 'adbe9f4e442a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old incompatible defaults first
    op.execute("ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT")

    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.text('now()'),
               postgresql_using="NOW()")
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.text('now()'),
               postgresql_using="NOW()")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
